name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x
      - name: install and tests
        run: |
          npm install
          npm run test
          npm run size
        env:
          CI: true
